# Generated by Django 4.2 on 2023-04-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_start_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('command', models.CharField(max_length=100)),
                ('command_end_date', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
