# Generated by Django 4.2 on 2023-04-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandapp', '0002_command_delete_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='file',
            new_name='output_file',
        ),
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.IntegerField(choices=[(0, 'Başarılı'), (1, 'Başarısız'), (2, 'Devam Ediyor')], default=2),
        ),
    ]
